# Generated by Django 5.2.8 on 2026-02-10 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Council', 'مجلس'), ('Ministry', 'وزارة'), ('Authority', 'هيئة'), ('Agency', 'مصلحة'), ('Company', 'شركة'), ('Affiliated', 'جهة تابعة'), ('Other', 'جهات أخرى')], max_length=50, verbose_name='نوع الجهة')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='الاسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
            ],
            options={
                'verbose_name': 'جهة',
                'verbose_name_plural': 'الجهات الاخرى',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubAffiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القسم التابع لجهة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
            ],
            options={
                'verbose_name': 'قسم تابع لجهة',
                'verbose_name_plural': 'الأقسام التابعة لجهة',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AffiliateDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.affiliate')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='microsys.scope', verbose_name='النطاق')),
                ('sub_affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.subaffiliate')),
            ],
            options={
                'verbose_name': 'قسم تابع لجهة',
                'verbose_name_plural': 'الأقسام التابعة لجهات',
                'default_permissions': (),
                'unique_together': {('affiliate', 'sub_affiliate')},
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='sub_affiliates',
            field=models.ManyToManyField(blank=True, related_name='affiliates', through='documents.AffiliateDepartment', to='documents.subaffiliate', verbose_name='الأقسام التابعة'),
        ),
    ]
